version: "2"

services:
  postgresdb:
      image: postgres:9.5
      environment:
        - POSTGRES_USER=${DB_BUILD_USER}
        - POSTGRES_PASSWORD=${DB_BUILD_PASS}
        - POSTGRES_DB=${DB_BUILD_NAME}
        - SCHEMASPY_SCHEMA=${SCHEMASPY_SCHEMA}
      ports:
        - '5432:5432'
      user: "$USER_ID"
      volumes:
          - ./database:/var/lib/postgresql/data
          - ./bkup:/bkup
          - /etc/passwd:/etc/passwd:ro
  schemaspy:
      build:
        context: ./schemaspy_build
        args:
          - PROXY=$PROXY
      volumes:
          - ./workspace/angular/schemaspy:/output
      links:
          - postgresdb:database
  programaacademicocrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$PROGRAMA_ACADEMICO_CRUD_GET_INFO;cd src/github.com/udistrital/$PROGRAMA_ACADEMICO_CRUD_GET_INFO;git checkout $PROGRAMA_ACADEMICO_CRUD_BRANCH_TARGET;git pull origin $PROGRAMA_ACADEMICO_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${PROGRAMA_ACADEMICO_CRUD_PORT}:${PROGRAMA_ACADEMICO_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  corecrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$CORE_CRUD_GET_INFO;cd src/github.com/udistrital/$CORE_CRUD_GET_INFO;git checkout $CORE_CRUD_BRANCH_TARGET;git pull origin $CORE_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${CORE_CRUD_PORT}:${CORE_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  experiencialaboralcrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$EXPERIENCIA_LABORAL_CRUD_GET_INFO;cd src/github.com/udistrital/$EXPERIENCIA_LABORAL_CRUD_GET_INFO;git checkout $EXPERIENCIA_LABORAL_CRUD_BRANCH_TARGET;git pull origin $EXPERIENCIA_LABORAL_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${EXPERIENCIA_LABORAL_CRUD_PORT}:${EXPERIENCIA_LABORAL_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  formacionacademicacrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$FORMACION_ACADEMICA_CRUD_GET_INFO;cd src/github.com/udistrital/$FORMACION_ACADEMICA_CRUD_GET_INFO;git checkout $FORMACION_ACADEMICA_CRUD_BRANCH_TARGET;git pull origin $FORMACION_ACADEMICA_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${FORMACION_ACADEMICA_CRUD_PORT}:${FORMACION_ACADEMICA_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  organizacioncrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$ORGANIZACION_CRUD_GET_INFO;cd src/github.com/udistrital/$ORGANIZACION_CRUD_GET_INFO;git checkout $ORGANIZACION_CRUD_BRANCH_TARGET;git pull origin $ORGANIZACION_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${ORGANIZACION_CRUD_PORT}:${ORGANIZACION_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  documentoscrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$DOCUMENTOS_CRUD_GET_INFO;cd src/github.com/udistrital/$DOCUMENTOS_CRUD_GET_INFO;git checkout $DOCUMENTOS_CRUD_BRANCH_TARGET;git pull origin $DOCUMENTOS_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${DOCUMENTOS_CRUD_PORT}:${DOCUMENTOS_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  personascrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$PERSONAS_CRUD_GET_INFO;cd src/github.com/udistrital/$PERSONAS_CRUD_GET_INFO;git checkout $PERSONAS_CRUD_BRANCH_TARGET;git pull origin $PERSONAS_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${PERSONAS_CRUD_PORT}:${PERSONAS_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  ubicacionescrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$UBICACIONES_CRUD_GET_INFO;cd src/github.com/udistrital/$UBICACIONES_CRUD_GET_INFO;git checkout $UBICACIONES_CRUD_BRANCH_TARGET;git pull origin $UBICACIONES_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${UBICACIONES_CRUD_PORT}:${UBICACIONES_CRUD_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  entecrud:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$ENTE_CRUD_GET_INFO;cd src/github.com/udistrital/$ENTE_CRUD_GET_INFO;git checkout $ENTE_CRUD_BRANCH_TARGET;git pull origin $ENTE_CRUD_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '${ENTE_HTTP_PORT}:${ENTE_HTTP_PORT}'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
  campusmid:
    #image: golang:1.8
    build:
      context: ./bee_build
      args:
          - PROXY=$PROXY
          - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'go get github.com/udistrital/$CAMPUS_MID_GET_INFO;cd src/github.com/udistrital/$CAMPUS_MID_GET_INFO;git checkout $CAMPUS_MID_BRANCH_TARGET;git pull origin $CAMPUS_MID_BRANCH_TARGET;bee run -downdoc=true -gendoc=true'
    ports:
      - '$CAMPUS_MID_PORT:$CAMPUS_MID_PORT'
    volumes:
      - ./workspace/go/src/github.com/udistrital/:/home/developer/go/src/github.com/udistrital/
      - /etc/passwd:/etc/passwd:ro
    user: "$USER_ID"
    depends_on:
      - postgresdb
      - ubicacionescrud
      - personascrud
      - documentoscrud
      - entecrud
  apache2:
    image: httpd:2.4-alpine
    ports:
     - "80:80"
    volumes:
     - ./apache2/sites-enabled:/etc/apache2/sites-enabled
     - ./workspace/angular:/usr/local/apache2/htdocs/
  client:
    build:
      context: ./genoas_build
      args:
        - PROXY=$PROXY
        - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'git clone https://github.com/udistrital/$CLIENT_CLONE_INFO.git ;cd $CLIENT_CLONE_INFO;git checkout $CLIENT_BRANCH_TARGET;git pull origin $CLIENT_BRANCH_TARGET;npm install;npm start'
    ports:
      - '$CLIENT_PORT:$CLIENT_PORT'
      - '35729:35729'
    depends_on:
      - ubicacionescrud
      - personascrud
      - documentoscrud
      - campusmid
    volumes:
      - ./workspace/angular:/workspace/angular
    user: "$USER_ID"
